sudo: false

language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"

services:
  - redis-server

install:
  - pip install -U pytest  # Travis comes with an old version pre-installed.
  - pip install -e .[tests]
  - pip freeze

script:
  - pytest

stages:
  - lint
  - test
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: lint
      install: pip install -U .[tests] black pyflakes isort
      script:
        - pyflakes .
        - black --check .
        - isort --check-only --diff --recursive channels_redis tests

    - stage: release
      script: skip
      deploy:
        provider: pypi
        user: andrewgodwin_bot
        on:
          tags: true
        distributions: sdist bdist_wheel
        password:
          secure: UHMwoR1zdoh1iBpZBUjQaWk80/q+xCWfjWhXTkgozL+/l3cpWFIzifBXxNNRwea9YDXy/4pitOYc8lzd9RtI1cZazjBTtd60A8UCT8yD3FY4qE27XJmyxzwNbcxdiWEd4ew4+kLhckbDDq/jXbBupndueCFHcTnbDjL/QJ8tPwihLnNZxDctRSlB1MkCEeQsQSSz70xSWvIiH5Qy1p6pR7MXdgk4X5/jWWomsuO0USMK+e1YXmhzSEboEUMcyzJfUqHE6Rct6PYQbUZLCGst4eIubLfoIXYbcg/Rv8SMvLKs4fuuNKbSdiWbykWf4wOduWcLt9plmuTKm1srjywNYSABUkj3whjIPPROts8TdraPcd2QhobtukIIDYpsKiOeL2nDHDz57sBkeoujqfnwmQx05YxTrcOhK1CNSB1oHUILP8VGabwcW4WLagRP0oNzAGbyu4WvazqTYDes/QBcpKPexrTFyGyUko7hDsBc4ZD9TRDTbk0IXfb81Qrao/cRGp4vT+KhsWsf4QQyNkghovp9llJLPq7MWXhSKcYsq0ilCjyKGPuxgyQyFA/9NoJKQl9pQgktF57N86piU/vjm+DS4JY/43tTudPJZ1LHuX5sk7zxhgpj3WTEuU4P0N8IyFuZSjy72dTO/A6QhjZWNRyztnpzeFJAs4zym0FySts=
