redis-master-1:
  build: testing/redis
redis-slave-1:
  build: testing/redis
  command: redis-server --slaveof redis-master-1 6379
  links:
    - redis-master-1
redis-master-2:
  build: testing/redis
redis-slave-2:
  build: testing/redis
  command: redis-server --slaveof redis-master-2 6379
  links:
    - redis-master-2
sentinel:
  build: testing/sentinel
  links:
    - redis-master-1
    - redis-master-2
    - redis-slave-1
    - redis-slave-2
test:
  build: .
  links:
    - redis-master-1
    - redis-master-2
    - redis-slave-1
    - redis-slave-2
    - sentinel
  volumes:
    - .:/src
